const test = require('ava')

const {CAG} = require('@jscad/csg')

const {serialize} = require('../index.js')

test('CAG to DXF', t => {
  const cag1 = new CAG()
  t.is(cag1.sides.length,0)

  const obs1 = serialize(cag1)
  const exp1 = [empty]
  t.deepEqual(obs1,exp1)

  const cag2 = CAG.rectangle()
  t.is(cag2.sides.length,4)

  const obs2 = serialize(cag2)
  const exp2 = [rectangle]
  t.deepEqual(obs2,exp2)
})

const empty = `999
DXF generated by OpenJsCad
  0
SECTION
  2
HEADER
  0
ENDSEC
  0
SECTION
  2
TABLES
  0
TABLE
  2
LTYPE
  70
1
  0
LTYPE
  2
CONTINUOUS
  3
Solid Line
  72
65
  73
0
  40
0.0
  0
ENDTAB
  0
TABLE
  2
LAYER
  70
1
  0
LAYER
  2
OpenJsCad
  62
7
  6
continuous
  0
ENDTAB
  0
TABLE
  2
STYLE
  70
0
  0
ENDTAB
  0
TABLE
  2
VIEW
  70
0
  0
ENDTAB
  0
ENDSEC
  0
SECTION
  2
BLOCKS
  0
ENDSEC
  0
SECTION
  2
ENTITIES
  0
ENDSEC
  0
EOF
`

const rectangle = `999
DXF generated by OpenJsCad
  0
SECTION
  2
HEADER
  0
ENDSEC
  0
SECTION
  2
TABLES
  0
TABLE
  2
LTYPE
  70
1
  0
LTYPE
  2
CONTINUOUS
  3
Solid Line
  72
65
  73
0
  40
0.0
  0
ENDTAB
  0
TABLE
  2
LAYER
  70
1
  0
LAYER
  2
OpenJsCad
  62
7
  6
continuous
  0
ENDTAB
  0
TABLE
  2
STYLE
  70
0
  0
ENDTAB
  0
TABLE
  2
VIEW
  70
0
  0
ENDTAB
  0
ENDSEC
  0
SECTION
  2
BLOCKS
  0
ENDSEC
  0
SECTION
  2
ENTITIES
  0
LWPOLYLINE
  8
OpenJsCad
  90
5
  70
1
 10
-1
 20
-1
 30
0.0
 10
1
 20
-1
 30
0.0
 10
1
 20
1
 30
0.0
 10
-1
 20
1
 30
0.0
 10
-1
 20
-1
 30
0.0
  0
ENDSEC
  0
EOF
`

