const test = require('ava')

const {CSG} = require('@jscad/csg')

const {serialize} = require('../index.js')
const {dxfHeaders, dxfClasses, dxfTables, dxfBlocks, dxfObjects} = require('../autocad_AC2017')

test('CSG to DXF 3DFACE', t => {
  const csg1 = new CSG()
  t.is(csg1.polygons.length,0)

  const obs1 = serialize({}, csg1)
  const exp1 = [empty]
  t.deepEqual(obs1,exp1)

  const csg2 = CSG.cube()
  t.is(csg2.polygons.length,6)

  const obs2 = serialize({}, csg2)
  const exp2 = [threeface1]
  t.deepEqual(obs2,exp2)
})

test('CSG to DXF POLYLINE FACES', t => {
  const csg1 = new CSG()
  t.is(csg1.polygons.length,0)

  const obs1 = serialize({csgTo: 'polyline'}, csg1)
  const exp1 = [empty]
  t.deepEqual(obs1,exp1)

  const csg2 = CSG.cube()
  t.is(csg2.polygons.length,6)

  const obs2 = serialize({csgTo: 'polyline'}, csg2)
  const exp2 = [polyline1]
  t.deepEqual(obs2,exp2)
})

const empty = `999
DXF generated by JSCAD
${dxfHeaders({})}
${dxfClasses({})}
${dxfTables({})}
${dxfBlocks({})}
  0
SECTION
  2
ENTITIES
  0
<<<<<<< HEAD
3DFACE
  5
CAD00052
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-0.4999999999999998
  20
1
  30
0.8660254037844387
  11
-1.7385635396170773
  21
1
  31
-0.8660254037844385
  12
-1.9418836348521042
  22
1
  32
-0.47863132857511487
  13
-1.9418836348521042
  23
1
  33
<<<<<<< HEAD
1
=======
-0.47863132857511487
>>>>>>> added test of complex CSG object, which ensures proper faces
  0
3DFACE
  5
CAD00053
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
<<<<<<< HEAD
-1
  20
-1
  30
-1
  11
-1
  21
1
  31
1
  12
-1
  22
1
  32
-1
  13
-1
  23
1
  33
-1
  0
3DFACE
  5
CAD00003
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
1
=======
-0.4999999999999998
>>>>>>> added test of complex CSG object, which ensures proper faces
  20
1
  30
0.8660254037844387
  11
-1.9418836348521042
  21
1
  31
-0.47863132857511487
  12
-1.9418836348521042
  22
1
  32
0.4786313285751145
  13
-1.9418836348521042
  23
<<<<<<< HEAD
1
  33
1
  0
3DFACE
  5
CAD00004
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
1
  20
-1
  30
-1
  11
1
  21
1
  31
1
  12
1
  22
-1
  32
1
  13
1
  23
-1
  33
=======
>>>>>>> added test of complex CSG object, which ensures proper faces
1
  33
0.4786313285751145
  0
3DFACE
  5
<<<<<<< HEAD
CAD00005
=======
CAD00054
>>>>>>> added test of complex CSG object, which ensures proper faces
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-0.4999999999999998
  20
1
  30
0.8660254037844387
  11
-1.9418836348521042
  21
1
  31
0.4786313285751145
  12
-1.7385635396170773
  22
1
  32
0.8660254037844386
  13
<<<<<<< HEAD
1
  23
-1
  33
1
  0
3DFACE
  5
CAD00006
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
-1
  30
-1
  11
1
  21
-1
  31
1
  12
-1
  22
-1
  32
1
  13
-1
=======
-1.7385635396170773
>>>>>>> added test of complex CSG object, which ensures proper faces
  23
1
  33
0.8660254037844386
  0
3DFACE
  5
<<<<<<< HEAD
CAD00007
=======
CAD00055
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
ENDSEC
${dxfObjects({})}
  0
EOF
`

const threeface1 = `999
DXF generated by JSCAD
${dxfHeaders({})}
${dxfClasses({})}
${dxfTables({})}
${dxfBlocks({})}
  0
SECTION
  2
ENTITIES
  0
3DFACE
  5
CAD00001
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
-1
  30
-1
  11
-1
  21
-1
  31
1
  12
-1
  22
1
  32
1
  13
-1
  23
1
  33
<<<<<<< HEAD
<<<<<<< HEAD
1
  0
3DFACE
  5
CAD00008
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
1
  30
-1
  11
1
  21
1
  31
1
  12
1
  22
1
  32
-1
  13
1
  23
1
  33
-1
  0
3DFACE
  5
CAD00009
=======
-0.8660254037844385
  0
3DFACE
  5
CAD00056
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
-1
  0
3DFACE
  5
CAD00002
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
1
  20
-1
  30
-1
  11
1
  21
1
  31
-1
  12
1
  22
1
  32
1
  13
1
  23
<<<<<<< HEAD
1
<<<<<<< HEAD
  33
-1
  0
3DFACE
  5
CAD0000A
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
-1
  30
-1
  11
1
  21
1
  31
-1
  12
1
  22
-1
  32
-1
  13
1
  23
-1
=======
>>>>>>> added test of complex CSG object, which ensures proper faces
  33
0
  0
3DFACE
  5
<<<<<<< HEAD
CAD0000B
=======
CAD00057
>>>>>>> added test of complex CSG object, which ensures proper faces
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-0.5000000000000004
  20
1
  30
-0.8660254037844385
  11
1.7865439091438067
  21
1
  31
-0.8660254037844385
  12
1.7709120513064207
  22
1
  32
-0.9294463440875352
  13
1.7709120513064207
  23
=======
-1
  33
>>>>>>> Reverted fixes to DXF serialize
1
  0
3DFACE
  5
CAD00003
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
-1
  30
-1
  11
1
  21
-1
  31
-1
  12
1
  22
-1
  32
1
  13
-1
  23
-1
  33
1
  0
3DFACE
  5
CAD00004
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
1
  30
-1
  11
-1
  21
1
  31
1
  12
1
  22
1
  32
1
  13
1
  23
1
  33
-1
  0
3DFACE
  5
CAD00005
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
-1
  30
-1
  11
-1
  21
1
  31
-1
  12
1
  22
1
  32
-1
  13
<<<<<<< HEAD
<<<<<<< HEAD
1
  23
1
  33
1
  0
3DFACE
  5
CAD0000C
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
-1
  30
1
  11
1
  21
1
  31
1
  12
-1
  22
1
  32
1
  13
-1
=======
-1.4970214963422022
>>>>>>> added test of complex CSG object, which ensures proper faces
  23
=======
>>>>>>> Reverted fixes to DXF serialize
1
  23
-1
  33
-1
  0
3DFACE
  5
CAD00006
  100
AcDbEntity
  8
0
  100
AcDbFace
  70
0
  10
-1
  20
-1
  30
1
  11
1
  21
-1
  31
1
  12
1
  22
1
  32
1
  13
-1
  23
1
  33
1
  0
ENDSEC
${dxfObjects({})}
  0
EOF
`

const polyline1 = `999
DXF generated by JSCAD
${dxfHeaders({})}
${dxfClasses({})}
${dxfTables({})}
${dxfBlocks({})}
  0
SECTION
  2
ENTITIES
  0
POLYLINE
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0000D
=======
CAD0005D
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00007
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDb3dPolyline
  70
64
  71
24
  72
6
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0000E
=======
CAD0005E
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00008
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
-1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0000F
=======
CAD0005F
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00009
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
-1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00010
=======
CAD00060
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0000A
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00011
=======
CAD00061
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0000B
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00012
=======
CAD00062
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0000C
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
-1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00013
=======
CAD00063
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0000D
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00014
=======
CAD00064
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0000E
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00015
=======
CAD00065
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0000F
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
-1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00016
=======
CAD00066
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00010
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
-1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00017
=======
CAD00067
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00011
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
-1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00018
=======
CAD00068
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00012
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
-1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00019
=======
CAD00069
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00013
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
-1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0001A
=======
CAD0006A
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00014
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0001B
=======
CAD0006B
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00015
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0001C
=======
CAD0006C
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00016
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0001D
=======
CAD0006D
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00017
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0001E
=======
CAD0006E
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00018
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
-1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0001F
=======
CAD0006F
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00019
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00020
=======
CAD00070
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0001A
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00021
=======
CAD00071
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0001B
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
-1
  30
-1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00022
=======
CAD00072
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0001C
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
-1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00023
=======
CAD00073
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0001D
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
-1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00024
=======
CAD00074
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0001E
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
1
  20
1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00025
=======
CAD00075
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD0001F
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
-1
  20
1
  30
1
  70
192
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00026
=======
CAD00076
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00020
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
0
  20
0
  30
0
  70
128
  71
1
  72
2
  73
3
  74
4
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00027
=======
CAD00077
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00021
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
0
  20
0
  30
0
  70
128
  71
5
  72
6
  73
7
  74
8
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00028
=======
CAD00078
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00022
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
0
  20
0
  30
0
  70
128
  71
9
  72
10
  73
11
  74
12
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD00029
=======
CAD00079
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00023
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
0
  20
0
  30
0
  70
128
  71
13
  72
14
  73
15
  74
16
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0002A
=======
CAD0007A
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00024
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
0
  20
0
  30
0
  70
128
  71
17
  72
18
  73
19
  74
20
  0
VERTEX
  5
<<<<<<< HEAD
<<<<<<< HEAD
CAD0002B
=======
CAD0007B
>>>>>>> added test of complex CSG object, which ensures proper faces
=======
CAD00025
>>>>>>> Reverted fixes to DXF serialize
  100
AcDbEntity
  8
0
  100
AcDbVertex
  100
AcDb3dPolylineVertex
  10
0
  20
0
  30
0
  70
128
  71
21
  72
22
  73
23
  74
24
  0
ENDSEC
${dxfObjects({})}
  0
EOF
`

